import { Quote, ShieldCheck, Target, Users } from "lucide-react";

import { Reveal } from "@/components/motion";
import { CtaBand, ImagePanel, PageHero, SectionTitle } from "@/components/page-parts";

export const metadata = { title: "About NOBEL | NOBEL Legal Consultancy" };

export default function AboutPage() {
  return (
    <>
      <PageHero eyebrow="About NOBEL" title="A legal consultancy built on trust and strategic thinking." copy="We combine professional rigor, UAE market understanding, and a long-term view of every client relationship." image="/images/boardroom.png" />
      <section className="py-24 md:py-32"><div className="section-shell grid gap-14 lg:grid-cols-2 lg:items-center"><div><SectionTitle eyebrow="Our Firm" title="Professional advice, grounded in the realities of business." copy="NOBEL Legal Consultancy was established to provide businesses and individuals with legal guidance that is reliable, considered, and practical. We believe the value of legal advice is measured not only by technical accuracy, but by its ability to support sound decisions." /><p className="mt-6 text-base leading-8 text-black/52">From our base in Sharjah, we support clients across the UAE with a strong understanding of the legal, regulatory, and commercial environment in which they operate.</p></div><ImagePanel src="/images/reception.jpeg" alt="NOBEL reception" className="aspect-[4/3]" /></div></section>
      <section className="bg-[#eeeae6] py-24 md:py-32"><div className="section-shell"><SectionTitle eyebrow="Our Foundation" title="The principles behind every engagement." /><div className="mt-12 grid gap-5 md:grid-cols-3">{[[Target, "Mission", "To provide clear legal strategies that protect interests and enable confident decisions."], [ShieldCheck, "Vision", "To be a trusted strategic legal partner for ambitious clients across the UAE."], [Users, "Values", "Trust, integrity, strategic thinking, excellence, and enduring relationships."]].map(([Icon, title, text], index) => <Reveal key={title as string} delay={index * .08}><div className="min-h-72 bg-white p-8"><Icon className="size-7 text-[#6a001a]" strokeWidth={1.4} /><h3 className="font-display mt-12 text-2xl">{title as string}</h3><p className="mt-4 text-sm leading-7 text-black/50">{text as string}</p></div></Reveal>)}</div></div></section>
      <section className="bg-[#1c1c1c] py-24 text-white md:py-32"><div className="section-shell grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><ImagePanel src="/images/hassan-al-wazir.jpeg" alt="Hassan Al Wazir" className="aspect-[4/4.5]" /><Reveal><Quote className="size-12 text-[#8c1533]" strokeWidth={1} /><span className="eyebrow mt-8 !text-[#dfadba]">Founder Message</span><blockquote className="font-display mt-6 text-2xl leading-[1.55] md:text-3xl">“At NOBEL Legal Consultancy, we believe professional legal consultancy is built on trust, integrity, strategic thinking, and long-term relationships.”</blockquote><div className="mt-7 space-y-4 text-sm leading-7 text-white/52"><p>Our mission has been to provide clients across the UAE with reliable legal guidance and practical solutions that support both business growth and legal protection.</p><p>We are proud of the reputation we have built through dedication, professionalism, and a deep understanding of the UAE market and legal environment. Your success and protection remain our priority.</p></div><p className="font-display mt-8 text-3xl italic text-[#d8aeba]">Hassan Al Wazir</p><p className="mt-2 text-xs tracking-[0.14em] text-white/38">SENIOR LEGAL CONSULTANT</p></Reveal></div></section>
      <CtaBand />
    </>
  );
}
